// Query TypeMap
import "@sanity/client";

/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type PortableText = Array<
	| {
			children?: Array<{
				marks?: Array<string>;
				text?: string;
				_type: "span";
				_key: string;
			}>;
			style?: "normal" | "h1" | "h2" | "h3" | "blockquote";
			listItem?: "bullet" | "number";
			markDefs?: Array<
				| {
						href: string;
						blank?: boolean;
						_type: "link";
						_key: string;
				  }
				| {
						phone: string;
						_type: "linkPhone";
						_key: string;
				  }
				| {
						email: string;
						_type: "linkEmail";
						_key: string;
				  }
			>;
			level?: number;
			_type: "block";
			_key: string;
	  }
	| {
			image: {
				asset?: {
					_ref: string;
					_type: "reference";
					_weak?: boolean;
					[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
				};
				media?: unknown;
				hotspot?: SanityImageHotspot;
				crop?: SanityImageCrop;
				_type: "image";
			};
			alt?: string;
			caption?: string;
			float?: "none" | "left" | "right";
			_type: "figure";
			_key: string;
	  }
	| {
			caption?: string;
			rows?: Array<{
				isHeader?: boolean;
				cells?: Array<string>;
				_type: "row";
				_key: string;
			}>;
			_type: "table";
			_key: string;
	  }
	| {
			tone?: "info" | "warning" | "danger";
			text: string;
			_type: "callout";
			_key: string;
	  }
>;

export type Settings = {
	_id: string;
	_type: "settings";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	works?: Array<{
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: "work";
	}>;
	contacts?: Array<{
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: "contact";
	}>;
	banner?: string;
	about?: PortableText;
	generalConditionsOfSale?: PortableText;
	legalNotices?: PortableText;
	privacyPolicy?: PortableText;
};

export type Contact = {
	_id: string;
	_type: "contact";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	url: string;
	text?: string;
	blank?: boolean;
};

export type Work = {
	_id: string;
	_type: "work";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title: string;
	slug: Slug;
	mainImage: {
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: "image";
	};
	tags?: Array<{
		_ref: string;
		_type: "reference";
		_weak?: boolean;
		_key: string;
		[internalGroqTypeReferenceTo]?: "tag";
	}>;
	text?: string;
	gallery?: Array<{
		asset?: {
			_ref: string;
			_type: "reference";
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: "image";
		_key: string;
	}>;
};

export type Tag = {
	_id: string;
	_type: "tag";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name: string;
	slug: Slug;
};

export type Markdown = string;

export type SanityImagePaletteSwatch = {
	_type: "sanity.imagePaletteSwatch";
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: "sanity.imagePalette";
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: "sanity.imageDimensions";
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageHotspot = {
	_type: "sanity.imageHotspot";
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type SanityImageCrop = {
	_type: "sanity.imageCrop";
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityFileAsset = {
	_id: string;
	_type: "sanity.fileAsset";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
	_id: string;
	_type: "sanity.imageAsset";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
	_type: "sanity.imageMetadata";
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type Geopoint = {
	_type: "geopoint";
	lat?: number;
	lng?: number;
	alt?: number;
};

export type Slug = {
	_type: "slug";
	current: string;
	source?: string;
};

export type SanityAssetSourceData = {
	_type: "sanity.assetSourceData";
	name?: string;
	id?: string;
	url?: string;
};

export type AllSanitySchemaTypes =
	| PortableText
	| Settings
	| Contact
	| Work
	| Tag
	| Markdown
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageHotspot
	| SanityImageCrop
	| SanityFileAsset
	| SanityImageAsset
	| SanityImageMetadata
	| Geopoint
	| Slug
	| SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanityBackend/lib/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "settings"][0]{    about  }
export type ABOUT_QUERYResult = {
	about: PortableText | null;
} | null;
// Variable: BANNET_QUERY
// Query: *[_type == "settings"][0]{    banner  }
export type BANNET_QUERYResult = {
	banner: string | null;
} | null;
// Variable: CONTACTS_QUERY
// Query: *[_type == "settings"][0]{    contacts[0...10]{      "_id": _key,      ...(@-> {        "slug": slug.current,        text,        title,        url,        blank      })    }  }
export type CONTACTS_QUERYResult = {
	contacts: Array<{
		_id: string;
		slug: string;
		text: string | null;
		title: string;
		url: string;
		blank: boolean | null;
	}> | null;
} | null;
// Variable: GENERAL_CONDITION_OF_SALE_QUERY
// Query: *[_type == "settings"][0]{    generalConditionsOfSale  }
export type GENERAL_CONDITION_OF_SALE_QUERYResult = {
	generalConditionsOfSale: PortableText | null;
} | null;
// Variable: LEGAL_NOTICES_QUERY
// Query: *[_type == "settings"][0]{    legalNotices  }
export type LEGAL_NOTICES_QUERYResult = {
	legalNotices: PortableText | null;
} | null;
// Variable: PRIVACY_POLICY_QUERY
// Query: *[_type == "settings"][0]{    privacyPolicy  }
export type PRIVACY_POLICY_QUERYResult = {
	privacyPolicy: PortableText | null;
} | null;
// Variable: WORKS_QUERY
// Query: *[_type == "settings"][0]{    "total": count(works),    works[$from...$to]{      "_id": _key,      ...(@-> {        "slug": slug.current,        title,        text,        mainImage{          alt,          "url": asset->url,          "width": asset->metadata.dimensions.width,          "height": asset->metadata.dimensions.height,          "lqip": asset->metadata.lqip,        },        "gallery": gallery[]{          alt,          "url": asset->url,          "_id": _key,          "width": asset->metadata.dimensions.width,          "height": asset->metadata.dimensions.height,          "blurHash": asset->metadata.blurHash,          "lqip": asset->metadata.lqip,        }      })    }  }
export type WORKS_QUERYResult = {
	total: number | null;
	works: Array<{
		_id: string;
		slug: string;
		title: string;
		text: string | null;
		mainImage: {
			alt: string | null;
			url: string | null;
			width: number | null;
			height: number | null;
			lqip: string | null;
		};
		gallery: Array<{
			alt: string | null;
			url: string | null;
			_id: string;
			width: number | null;
			height: number | null;
			blurHash: string | null;
			lqip: string | null;
		}> | null;
	}> | null;
} | null;
// Variable: WORK_QUERY
// Query: *[_type == "work" && slug.current == $slug][0]{    _id,    "slug": slug.current,    title,    text,    mainImage{      alt,      "url": asset->url,      "width": asset->metadata.dimensions.width,      "height": asset->metadata.dimensions.height,      "lqip": asset->metadata.lqip,    },    "gallery": gallery[]{      alt,      "url": asset->url,      "_id": _key,      "width": asset->metadata.dimensions.width,      "height": asset->metadata.dimensions.height,      "blurHash": asset->metadata.blurHash,      "lqip": asset->metadata.lqip,    }  }
export type WORK_QUERYResult = {
	_id: string;
	slug: string;
	title: string;
	text: string | null;
	mainImage: {
		alt: string | null;
		url: string | null;
		width: number | null;
		height: number | null;
		lqip: string | null;
	};
	gallery: Array<{
		alt: string | null;
		url: string | null;
		_id: string;
		width: number | null;
		height: number | null;
		blurHash: string | null;
		lqip: string | null;
	}> | null;
} | null;

declare module "@sanity/client" {
	interface SanityQueries {
		'\n  *[_type == "settings"][0]{\n    about\n  }  \n': ABOUT_QUERYResult;
		'\n  *[_type == "settings"][0]{\n    banner\n  }\n': BANNET_QUERYResult;
		'\n  *[_type == "settings"][0]{\n    contacts[0...10]{\n      "_id": _key,\n      ...(@-> {\n        "slug": slug.current,\n        text,\n        title,\n        url,\n        blank\n      })\n    }\n  }\n': CONTACTS_QUERYResult;
		'\n  *[_type == "settings"][0]{\n    generalConditionsOfSale\n  }\n': GENERAL_CONDITION_OF_SALE_QUERYResult;
		'\n  *[_type == "settings"][0]{\n    legalNotices\n  }  \n': LEGAL_NOTICES_QUERYResult;
		'\n  *[_type == "settings"][0]{\n    privacyPolicy\n  }\n': PRIVACY_POLICY_QUERYResult;
		'\n  *[_type == "settings"][0]{\n    "total": count(works),\n    works[$from...$to]{\n      "_id": _key,\n      ...(@-> {\n        "slug": slug.current,\n        title,\n        text,\n        mainImage{\n          alt,\n          "url": asset->url,\n          "width": asset->metadata.dimensions.width,\n          "height": asset->metadata.dimensions.height,\n          "lqip": asset->metadata.lqip,\n        },\n        "gallery": gallery[]{\n          alt,\n          "url": asset->url,\n          "_id": _key,\n          "width": asset->metadata.dimensions.width,\n          "height": asset->metadata.dimensions.height,\n          "blurHash": asset->metadata.blurHash,\n          "lqip": asset->metadata.lqip,\n        }\n      })\n    }\n  }\n': WORKS_QUERYResult;
		'\n  *[_type == "work" && slug.current == $slug][0]{\n    _id,\n    "slug": slug.current,\n    title,\n    text,\n    mainImage{\n      alt,\n      "url": asset->url,\n      "width": asset->metadata.dimensions.width,\n      "height": asset->metadata.dimensions.height,\n      "lqip": asset->metadata.lqip,\n    },\n    "gallery": gallery[]{\n      alt,\n      "url": asset->url,\n      "_id": _key,\n      "width": asset->metadata.dimensions.width,\n      "height": asset->metadata.dimensions.height,\n      "blurHash": asset->metadata.blurHash,\n      "lqip": asset->metadata.lqip,\n    }\n  }  \n': WORK_QUERYResult;
	}
}
