// Query TypeMap
import "@sanity/client";

/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanityBackend/extract.json
export type SanityImageAssetReference = {
	_ref: string;
	_type: "reference";
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type FigureImage = {
	asset?: SanityImageAssetReference;
	media?: unknown; // Unable to locate the referenced type "media" in schema
	hotspot?: SanityImageHotspot;
	crop?: SanityImageCrop;
	_type: "image";
};

export type TagReference = {
	_ref: string;
	_type: "reference";
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: "tag";
};

export type Work = {
	_id: string;
	_type: "work";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	orderRank?: string;
	hidden?: boolean;
	title: string;
	slug: Slug;
	mainImage: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: "image";
	};
	tags?: Array<
		{
			_key: string;
		} & TagReference
	>;
	text?: string;
	gallery?: Array<{
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		_type: "image";
		_key: string;
	}>;
};

export type SanityImageCrop = {
	_type: "sanity.imageCrop";
	top: number;
	bottom: number;
	left: number;
	right: number;
};

export type SanityImageHotspot = {
	_type: "sanity.imageHotspot";
	x: number;
	y: number;
	height: number;
	width: number;
};

export type Slug = {
	_type: "slug";
	current: string;
	source?: string;
};

export type Tag = {
	_id: string;
	_type: "tag";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	name: string;
	slug: Slug;
};

export type Settings = {
	_id: string;
	_type: "settings";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	banner?: string;
};

export type PrivacyPolicy = {
	_id: string;
	_type: "privacyPolicy";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	content?: PortableText;
};

export type PortableText = Array<
	| {
			children?: Array<{
				marks?: Array<string>;
				text?: string;
				_type: "span";
				_key: string;
			}>;
			style?: "normal" | "h1" | "h2" | "h3" | "blockquote";
			listItem?: "bullet" | "number";
			markDefs?: Array<
				| {
						href: string;
						blank?: boolean;
						_type: "link";
						_key: string;
				  }
				| {
						phone: string;
						_type: "linkPhone";
						_key: string;
				  }
				| {
						email: string;
						_type: "linkEmail";
						_key: string;
				  }
			>;
			level?: number;
			_type: "block";
			_key: string;
	  }
	| {
			image: FigureImage;
			alt?: string;
			caption?: string;
			float?: "none" | "left" | "right";
			_type: "figure";
			_key: string;
	  }
	| {
			caption?: string;
			rows?: Array<{
				isHeader?: boolean;
				cells?: Array<string>;
				_type: "row";
				_key: string;
			}>;
			_type: "table";
			_key: string;
	  }
	| {
			tone?: "info" | "warning" | "danger";
			text: string;
			_type: "callout";
			_key: string;
	  }
>;

export type LegalNotices = {
	_id: string;
	_type: "legalNotices";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	content?: PortableText;
};

export type GeneralConditionsOfSale = {
	_id: string;
	_type: "generalConditionsOfSale";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	content?: PortableText;
};

export type Contact = {
	_id: string;
	_type: "contact";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	orderRank?: string;
	hidden?: boolean;
	title: string;
	slug: Slug;
	url: string;
	text?: string;
	blank?: boolean;
};

export type About = {
	_id: string;
	_type: "about";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	content?: PortableText;
};

export type Markdown = string;

export type SanityImagePaletteSwatch = {
	_type: "sanity.imagePaletteSwatch";
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: "sanity.imagePalette";
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: "sanity.imageDimensions";
	height: number;
	width: number;
	aspectRatio: number;
};

export type SanityImageMetadata = {
	_type: "sanity.imageMetadata";
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	thumbHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: "sanity.fileAsset";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash: string;
	extension: string;
	mimeType: string;
	size: number;
	assetId: string;
	uploadId?: string;
	path: string;
	url: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: "sanity.assetSourceData";
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: "sanity.imageAsset";
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash: string;
	extension: string;
	mimeType: string;
	size: number;
	assetId: string;
	uploadId?: string;
	path: string;
	url: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: "geopoint";
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| SanityImageAssetReference
	| FigureImage
	| TagReference
	| Work
	| SanityImageCrop
	| SanityImageHotspot
	| Slug
	| Tag
	| Settings
	| PrivacyPolicy
	| PortableText
	| LegalNotices
	| GeneralConditionsOfSale
	| Contact
	| About
	| Markdown
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;

// Source: sanityBackend/lib/queries.ts
// Variable: ABOUT_QUERY
// Query: *[_type == "about"][0]{    content[]{      ...,      _type == "figure" => {        ...,        "image": image{          ...,          "width": asset->metadata.dimensions.width,          "height": asset->metadata.dimensions.height,          "lqip": asset->metadata.lqip        }      }    },  }
export type ABOUT_QUERY_RESULT = {
	content: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: "span";
					_key: string;
				}>;
				style?: "blockquote" | "h1" | "h2" | "h3" | "normal";
				listItem?: "bullet" | "number";
				markDefs?: Array<
					| {
							href: string;
							blank?: boolean;
							_type: "link";
							_key: string;
					  }
					| {
							email: string;
							_type: "linkEmail";
							_key: string;
					  }
					| {
							phone: string;
							_type: "linkPhone";
							_key: string;
					  }
				>;
				level?: number;
				_type: "block";
				_key: string;
		  }
		| {
				tone?: "danger" | "info" | "warning";
				text: string;
				_type: "callout";
				_key: string;
		  }
		| {
				image: {
					asset?: SanityImageAssetReference;
					media?: unknown; // Unable to locate the referenced type "media" in schema
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: "image";
					width: number | null;
					height: number | null;
					lqip: string | null;
				};
				alt?: string;
				caption?: string;
				float?: "left" | "none" | "right";
				_type: "figure";
				_key: string;
		  }
		| {
				caption?: string;
				rows?: Array<{
					isHeader?: boolean;
					cells?: Array<string>;
					_type: "row";
					_key: string;
				}>;
				_type: "table";
				_key: string;
		  }
	> | null;
} | null;

// Source: sanityBackend/lib/queries.ts
// Variable: BANNET_QUERY
// Query: *[_type == "settings"][0]{    banner  }
export type BANNET_QUERY_RESULT = {
	banner: string | null;
} | null;

// Source: sanityBackend/lib/queries.ts
// Variable: CONTACTS_QUERY
// Query: *[_type == "contact" && (hidden == false || !defined(hidden))] | order(orderRank) [0...10]{    _id,    "slug": slug.current,    text,    title,    url,    blank  }
export type CONTACTS_QUERY_RESULT = Array<{
	_id: string;
	slug: string;
	text: string | null;
	title: string;
	url: string;
	blank: boolean | null;
}>;

// Source: sanityBackend/lib/queries.ts
// Variable: GENERAL_CONDITION_OF_SALE_QUERY
// Query: *[_type == "generalConditionsOfSale"][0]{    content[]{      ...,      _type == "figure" => {        ...,        "image": image{          ...,          "width": asset->metadata.dimensions.width,          "height": asset->metadata.dimensions.height,          "lqip": asset->metadata.lqip        }      }    },    _updatedAt  }
export type GENERAL_CONDITION_OF_SALE_QUERY_RESULT = {
	content: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: "span";
					_key: string;
				}>;
				style?: "blockquote" | "h1" | "h2" | "h3" | "normal";
				listItem?: "bullet" | "number";
				markDefs?: Array<
					| {
							href: string;
							blank?: boolean;
							_type: "link";
							_key: string;
					  }
					| {
							email: string;
							_type: "linkEmail";
							_key: string;
					  }
					| {
							phone: string;
							_type: "linkPhone";
							_key: string;
					  }
				>;
				level?: number;
				_type: "block";
				_key: string;
		  }
		| {
				tone?: "danger" | "info" | "warning";
				text: string;
				_type: "callout";
				_key: string;
		  }
		| {
				image: {
					asset?: SanityImageAssetReference;
					media?: unknown; // Unable to locate the referenced type "media" in schema
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: "image";
					width: number | null;
					height: number | null;
					lqip: string | null;
				};
				alt?: string;
				caption?: string;
				float?: "left" | "none" | "right";
				_type: "figure";
				_key: string;
		  }
		| {
				caption?: string;
				rows?: Array<{
					isHeader?: boolean;
					cells?: Array<string>;
					_type: "row";
					_key: string;
				}>;
				_type: "table";
				_key: string;
		  }
	> | null;
	_updatedAt: string;
} | null;

// Source: sanityBackend/lib/queries.ts
// Variable: LEGAL_NOTICES_QUERY
// Query: *[_type == "legalNotices"][0]{    content[]{      ...,      _type == "figure" => {        ...,        "image": image{          ...,          "width": asset->metadata.dimensions.width,          "height": asset->metadata.dimensions.height,          "lqip": asset->metadata.lqip        }      }    },    _updatedAt  }
export type LEGAL_NOTICES_QUERY_RESULT = {
	content: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: "span";
					_key: string;
				}>;
				style?: "blockquote" | "h1" | "h2" | "h3" | "normal";
				listItem?: "bullet" | "number";
				markDefs?: Array<
					| {
							href: string;
							blank?: boolean;
							_type: "link";
							_key: string;
					  }
					| {
							email: string;
							_type: "linkEmail";
							_key: string;
					  }
					| {
							phone: string;
							_type: "linkPhone";
							_key: string;
					  }
				>;
				level?: number;
				_type: "block";
				_key: string;
		  }
		| {
				tone?: "danger" | "info" | "warning";
				text: string;
				_type: "callout";
				_key: string;
		  }
		| {
				image: {
					asset?: SanityImageAssetReference;
					media?: unknown; // Unable to locate the referenced type "media" in schema
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: "image";
					width: number | null;
					height: number | null;
					lqip: string | null;
				};
				alt?: string;
				caption?: string;
				float?: "left" | "none" | "right";
				_type: "figure";
				_key: string;
		  }
		| {
				caption?: string;
				rows?: Array<{
					isHeader?: boolean;
					cells?: Array<string>;
					_type: "row";
					_key: string;
				}>;
				_type: "table";
				_key: string;
		  }
	> | null;
	_updatedAt: string;
} | null;

// Source: sanityBackend/lib/queries.ts
// Variable: PRIVACY_POLICY_QUERY
// Query: *[_type == "privacyPolicy"][0]{    content[]{      ...,      _type == "figure" => {        ...,        "image": image{          ...,          "width": asset->metadata.dimensions.width,          "height": asset->metadata.dimensions.height,          "lqip": asset->metadata.lqip        }      }    },    _updatedAt  }
export type PRIVACY_POLICY_QUERY_RESULT = {
	content: Array<
		| {
				children?: Array<{
					marks?: Array<string>;
					text?: string;
					_type: "span";
					_key: string;
				}>;
				style?: "blockquote" | "h1" | "h2" | "h3" | "normal";
				listItem?: "bullet" | "number";
				markDefs?: Array<
					| {
							href: string;
							blank?: boolean;
							_type: "link";
							_key: string;
					  }
					| {
							email: string;
							_type: "linkEmail";
							_key: string;
					  }
					| {
							phone: string;
							_type: "linkPhone";
							_key: string;
					  }
				>;
				level?: number;
				_type: "block";
				_key: string;
		  }
		| {
				tone?: "danger" | "info" | "warning";
				text: string;
				_type: "callout";
				_key: string;
		  }
		| {
				image: {
					asset?: SanityImageAssetReference;
					media?: unknown; // Unable to locate the referenced type "media" in schema
					hotspot?: SanityImageHotspot;
					crop?: SanityImageCrop;
					_type: "image";
					width: number | null;
					height: number | null;
					lqip: string | null;
				};
				alt?: string;
				caption?: string;
				float?: "left" | "none" | "right";
				_type: "figure";
				_key: string;
		  }
		| {
				caption?: string;
				rows?: Array<{
					isHeader?: boolean;
					cells?: Array<string>;
					_type: "row";
					_key: string;
				}>;
				_type: "table";
				_key: string;
		  }
	> | null;
	_updatedAt: string;
} | null;

// Source: sanityBackend/lib/queries.ts
// Variable: WORKS_QUERY
// Query: {    "total": count(*[_type == "work" && (hidden == false || !defined(hidden))]),    "works": *[_type == "work" && (hidden == false || !defined(hidden))] | order(orderRank) [$from...$to]{      _id,      "slug": slug.current,      title,      text,      mainImage{        alt,        "url": asset->url,        "width": asset->metadata.dimensions.width,        "height": asset->metadata.dimensions.height,        "lqip": asset->metadata.lqip,      },      "gallery": gallery[]{        "_id": _key,        alt,        "url": asset->url,        "width": asset->metadata.dimensions.width,        "height": asset->metadata.dimensions.height,        "blurHash": asset->metadata.blurHash,        "lqip": asset->metadata.lqip,      }    }  }
export type WORKS_QUERY_RESULT = {
	total: number;
	works: Array<{
		_id: string;
		slug: string;
		title: string;
		text: string | null;
		mainImage: {
			alt: string | null;
			url: string | null;
			width: number | null;
			height: number | null;
			lqip: string | null;
		};
		gallery: Array<{
			_id: string;
			alt: string | null;
			url: string | null;
			width: number | null;
			height: number | null;
			blurHash: string | null;
			lqip: string | null;
		}> | null;
	}>;
};

// Source: sanityBackend/lib/queries.ts
// Variable: WORK_QUERY
// Query: *[_type == "work" && (hidden == false || !defined(hidden)) && slug.current == $slug][0]{    _id,    "slug": slug.current,    title,    text,    mainImage{      alt,      "url": asset->url,      "width": asset->metadata.dimensions.width,      "height": asset->metadata.dimensions.height,      "lqip": asset->metadata.lqip,    },    "gallery": gallery[]{      alt,      "url": asset->url,      "_id": _key,      "width": asset->metadata.dimensions.width,      "height": asset->metadata.dimensions.height,      "blurHash": asset->metadata.blurHash,      "lqip": asset->metadata.lqip,    }  }
export type WORK_QUERY_RESULT = {
	_id: string;
	slug: string;
	title: string;
	text: string | null;
	mainImage: {
		alt: string | null;
		url: string | null;
		width: number | null;
		height: number | null;
		lqip: string | null;
	};
	gallery: Array<{
		alt: string | null;
		url: string | null;
		_id: string;
		width: number | null;
		height: number | null;
		blurHash: string | null;
		lqip: string | null;
	}> | null;
} | null;

declare module "@sanity/client" {
	interface SanityQueries {
		'\n  *[_type == "about"][0]{\n    content[]{\n      ...,\n      _type == "figure" => {\n        ...,\n        "image": image{\n          ...,\n          "width": asset->metadata.dimensions.width,\n          "height": asset->metadata.dimensions.height,\n          "lqip": asset->metadata.lqip\n        }\n      }\n    },\n  }\n': ABOUT_QUERY_RESULT;
		'\n  *[_type == "settings"][0]{\n    banner\n  }\n': BANNET_QUERY_RESULT;
		'\n  *[_type == "contact" && (hidden == false || !defined(hidden))] | order(orderRank) [0...10]{\n    _id,\n    "slug": slug.current,\n    text,\n    title,\n    url,\n    blank\n  }\n': CONTACTS_QUERY_RESULT;
		'\n  *[_type == "generalConditionsOfSale"][0]{\n    content[]{\n      ...,\n      _type == "figure" => {\n        ...,\n        "image": image{\n          ...,\n          "width": asset->metadata.dimensions.width,\n          "height": asset->metadata.dimensions.height,\n          "lqip": asset->metadata.lqip\n        }\n      }\n    },\n    _updatedAt\n  }\n': GENERAL_CONDITION_OF_SALE_QUERY_RESULT;
		'\n  *[_type == "legalNotices"][0]{\n    content[]{\n      ...,\n      _type == "figure" => {\n        ...,\n        "image": image{\n          ...,\n          "width": asset->metadata.dimensions.width,\n          "height": asset->metadata.dimensions.height,\n          "lqip": asset->metadata.lqip\n        }\n      }\n    },\n    _updatedAt\n  }\n': LEGAL_NOTICES_QUERY_RESULT;
		'\n  *[_type == "privacyPolicy"][0]{\n    content[]{\n      ...,\n      _type == "figure" => {\n        ...,\n        "image": image{\n          ...,\n          "width": asset->metadata.dimensions.width,\n          "height": asset->metadata.dimensions.height,\n          "lqip": asset->metadata.lqip\n        }\n      }\n    },\n    _updatedAt\n  }\n': PRIVACY_POLICY_QUERY_RESULT;
		'\n  {\n    "total": count(*[_type == "work" && (hidden == false || !defined(hidden))]),\n    "works": *[_type == "work" && (hidden == false || !defined(hidden))] | order(orderRank) [$from...$to]{\n      _id,\n      "slug": slug.current,\n      title,\n      text,\n      mainImage{\n        alt,\n        "url": asset->url,\n        "width": asset->metadata.dimensions.width,\n        "height": asset->metadata.dimensions.height,\n        "lqip": asset->metadata.lqip,\n      },\n      "gallery": gallery[]{\n        "_id": _key,\n        alt,\n        "url": asset->url,\n        "width": asset->metadata.dimensions.width,\n        "height": asset->metadata.dimensions.height,\n        "blurHash": asset->metadata.blurHash,\n        "lqip": asset->metadata.lqip,\n      }\n    }\n  }\n': WORKS_QUERY_RESULT;
		'\n  *[_type == "work" && (hidden == false || !defined(hidden)) && slug.current == $slug][0]{\n    _id,\n    "slug": slug.current,\n    title,\n    text,\n    mainImage{\n      alt,\n      "url": asset->url,\n      "width": asset->metadata.dimensions.width,\n      "height": asset->metadata.dimensions.height,\n      "lqip": asset->metadata.lqip,\n    },\n    "gallery": gallery[]{\n      alt,\n      "url": asset->url,\n      "_id": _key,\n      "width": asset->metadata.dimensions.width,\n      "height": asset->metadata.dimensions.height,\n      "blurHash": asset->metadata.blurHash,\n      "lqip": asset->metadata.lqip,\n    }\n  }  \n': WORK_QUERY_RESULT;
	}
}
